name: FlyFishJen
favicon: null
layout_spectrum: 0.68188
typography_spectrum: 0.977748982841149
title: A peek into my fly fishing life.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76316737-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8525602973531932
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
